// SAMPLES/frameworks/hello-world-solidjs/webview-ui/src/App.tsx
import type { Component } from "solid-js";
import { provideVSCodeDesignSystem, vsCodeButton } from "darbot-webview-ui";
import { vscode } from "./utilities/vscode";
import "./App.css";

// In order to use the DarBot Webview UI Toolkit web components they
// must be registered with the browser (i.e. webview) using the
// syntax below.
provideVSCodeDesignSystem().register(vsCodeButton());

// To register more toolkit components, simply import the component
// registration function and call it from within the register
// function, like so:
//
// provideVSCodeDesignSystem().register(
//   vsCodeButton(),
//   vsCodeCheckbox()
// );
//
// Finally, if you would like to register all of the toolkit
// components at once, there's a handy convenience function:
//
// provideVSCodeDesignSystem().register(allComponents);

const App: Component = () => {
  function handleHowdyClick() {
    vscode.postMessage({
      command: "hello",
      text: "Hey there partner! 🤠",
    });
  }

  return (
    <main>
      <h1>Hello world!</h1>
      <vscode-button onClick={handleHowdyClick}>Howdy!</vscode-button>
    </main>
  );
};

export default App;

// SAMPLES/frameworks/hello-world-angular/webview-ui/src/app/app.component.ts
import {Component} from '@angular/core';
import {provideVSCodeDesignSystem, vsCodeButton} from 'darbot-webview-ui';
import {vscode} from './utilities/vscode';

// In order to use the DarBot Webview UI Toolkit web components they
// must be registered with the browser (i.e. webview) using the
// syntax below.
provideVSCodeDesignSystem().register(vsCodeButton());

// To register more toolkit components, simply import the component
// registration function and call it from within the register
// function, like so:
//
// provideVSCodeDesignSystem().register(
//   vsCodeButton(),
//   vsCodeCheckbox()
// );
//
// Finally, if you would like to register all of the toolkit
// components at once, there's a handy convenience function:
//
// provideVSCodeDesignSystem().register(allComponents);

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.css'],
})
export class AppComponent {
	title = 'hello-world';

	handleHowdyClick() {
		vscode.postMessage({
			command: 'hello',
			text: 'Hey there partner! 🤠',
		});
	}
}
